# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newsRecommendationSystem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enewsRecommendationSystem.proto\x12\x0fnews.hamropatro\"-\n\nNRSRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"+\n\x08NRSReply\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t2N\n\nNRSService\x12@\n\x04send\x12\x1b.news.hamropatro.NRSRequest\x1a\x19.news.hamropatro.NRSReply\"\x00\x42\x33\n\x0fnews.hamropatroB\x18NewsRecommendationSystemP\x01\xa2\x02\x03HLWb\x06proto3')



_NRSREQUEST = DESCRIPTOR.message_types_by_name['NRSRequest']
_NRSREPLY = DESCRIPTOR.message_types_by_name['NRSReply']
NRSRequest = _reflection.GeneratedProtocolMessageType('NRSRequest', (_message.Message,), {
  'DESCRIPTOR' : _NRSREQUEST,
  '__module__' : 'newsRecommendationSystem_pb2'
  # @@protoc_insertion_point(class_scope:news.hamropatro.NRSRequest)
  })
_sym_db.RegisterMessage(NRSRequest)

NRSReply = _reflection.GeneratedProtocolMessageType('NRSReply', (_message.Message,), {
  'DESCRIPTOR' : _NRSREPLY,
  '__module__' : 'newsRecommendationSystem_pb2'
  # @@protoc_insertion_point(class_scope:news.hamropatro.NRSReply)
  })
_sym_db.RegisterMessage(NRSReply)

_NRSSERVICE = DESCRIPTOR.services_by_name['NRSService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017news.hamropatroB\030NewsRecommendationSystemP\001\242\002\003HLW'
  _NRSREQUEST._serialized_start=51
  _NRSREQUEST._serialized_end=96
  _NRSREPLY._serialized_start=98
  _NRSREPLY._serialized_end=141
  _NRSSERVICE._serialized_start=143
  _NRSSERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
